-- 3a
SELECT NAME, WOHNORT 
FROM MITGlIEDER;

-- 3b
SELECT DISTINCT ANG.ANR 
FROM ANGESTELLTE ANG
INNER JOIN REGISTRIERUNGEN REG ON (REG.ANR = ANG.ANR);

-- 3c
SELECT MNR, DVDNR, DATUM, RUECKGABE-DATUM AS DAUER
FROM AUSLEIHEN;

-- 3d
SELECT MNR, DVDNR, DATUM, ROUND((NVL(RUECKGABE, SYSDATE) - DATUM)) AS DAUER
FROM AUSLEIHEN;

-- 3e
SELECT LOWER(SUBSTR(NAME,1,2)) AS KUERZEL
FROM ANGESTELLTE;

-- 3f
SELECT SUBSTR(GDATUM, -2, 2), TO_CHAR(GDATUM,'YY')    
FROM MITGLIEDER;

-- 3g
SELECT DISTINCT 'ORACLE IST GANZ EINFACH'
FROM REGISTRIERUNGEN;

-- 3h
SELECT /*csv*/ *
FROM FILIALEN;

-- 3i
SELECT USER, USERENV('LANG'), USERENV('ISDBA'), TRIM('    a'), TO_DATE('10/28/2016','MM/DD/YYYY') 
FROM DUAL;

-- 3j
SELECT TO_CHAR(TO_DATE(MINDESTALTER,'j'), 'jsp')
FROM FILME;

-- 3k
SELECT ANR, ROWNUM, ROWID, ROWNUM * 2
FROM REGISTRIERUNGEN
WHERE ANR = 'A01';

-- 4a
SELECT MNR, DVDNR
FROM AUSLEIHEN
WHERE TO_NUMBER(TO_CHAR(RUECKGABE, 'YYYY')) = 2013;

SELECT MNR, DVDNR
FROM AUSLEIHEN
WHERE EXTRACT(YEAR FROM RUECKGABE) = 2013;

-- 4a
SELECT MNR, DVDNR
FROM AUSLEIHEN
WHERE TO_NUMBER(TO_CHAR(RUECKGABE, 'YYYY')) = 2013;

-- 4b
SELECT MNR, DVDNR
FROM AUSLEIHEN
WHERE TO_NUMBER(TO_CHAR(RUECKGABE, 'YYYY')) <> 2007;

-- 4c
SELECT MNR, DVDNR
FROM AUSLEIHEN
WHERE (TO_NUMBER(TO_CHAR(RUECKGABE, 'YYYY')) <> 2007) OR (RUECKGABE IS NULL);

-- 4e
SELECT rueckgabe
FROM ausleihen
WHERE mnr = 'M003';

-- 4f
SELECT mnr, dvdnr
FROM ausleihen
WHERE rueckgabe IS NULL;

-- 4g
SELECT *
FROM mitglieder
WHERE (SYSDATE - gdatum) > 35;

-- 4h
SELECT *
FROM angestellte
WHERE LOWER(name) LIKE '%r%';

-- 4i
SELECT datum, dvdnr
FROM ausleihen
WHERE mnr IN ('M002', 'M004');

-- 4j
SELECT *
FROM filme
WHERE mindestalter BETWEEN 7 AND 12;